### ISSUE TITLE
Unable to install in Rio 10.3.1

### ISSUE THREAD

**Issue by pka4916** [landrix/The-Drag-and-Drop-Component-Suite-for-Delphi#32]
After compiling, I am trying to install the package, and keep getting the error 
that it cannot find a package in the folder.  
Everything is there, so I don't know what else it's looking for.

**Comment by birkangit** [comment]
I had the same issue. Opening DragDropDR102TGroup.groupproj and installing with these packages for 10.3 the problem solved.

**Comment by pka4916** [comment]
That seems to work,  but then I don't have Windows 64 Bit support.

**Comment by birkangit** [comment]
> That seems to work, but then I don't have Windows 64 Bit support.

1. Install with DragDropDR102TGroup.groupproj (32 bit) 
2. Add DragDropComponentSuite\Source folder to your library path for both 32 bit and 64 bit platform.  

You can now compile your application with 64 bit support.

**Comment by AlpDmr** [comment]
> 
> 
> After compiling, I am trying to install the package, and keep getting the error
> that it cannot find a package in the folder.
> Everything is there, so I don't know what else it's looking for.

Same problem for me as well..

**Comment by NamoRamana** [comment]
> After compiling, I am trying to install the package, and keep getting the error
> that it cannot find a package in the folder.
> Everything is there, so I don't know what else it's looking for.

I faced the same issue.  Can you please fix the packages for 10.3.X, instead of installing packages for 10.2 in 10.3, as @birkangit suggested?

**Comment by NamoRamana** [comment]
Update: As @birkangit suggested, In Delphi 10.3.1 IDE, I opened DragDropDR102TGroup.groupproj. Thereafter, the things that did not work were: I changed the dcp/dcu/package output path to a custom dir and after successful compilation, tried to install from the custom path. Got the same error .. "module not found.." or some. So deleted all generated binaries from the custom folder. And this time, I went with default settings of the project options as came with fresh downloaded source code. And this time ti worked. After installation of the components, when I checked from where the .bpl was installed, it was found at <drive>\Users\Public\Documents\Embarcadero\Studio\20.0\Bpl\dclDragDropDR012T.bpl. the issue seems to be that, at the time of installation, its looking for the .bpl in that "public\documents\..." folder.

**Comment by landrix** [comment]
- open DragDropDR103RGroup.groupproj and compile both projects for all platforms
- bpl and dcu will be generated under Library\DX103R\Win32_Release and Library\DX103R\Win64_Release

if you don't want to add this directories to IDE Lib Path, then change the project settings or copy files to where you need.... for instance
\Users\Public\Documents\Embarcadero\Studio\20.0\Bpl
\Users\Public\Documents\Embarcadero\Studio\20.0\Dcu

**Comment by NamoRamana** [comment]
Thank you @landrix for your reply. Following sequence worked for me (with one error at the end. Greatly appreciate if you can confirm it).
(1) Opened DragDropDR103RGroup.groupproj (both projects, set to 32 bit)
(2) First compiled project DragDropDR103R.bpl. Copied DragDropDR103R.bpl and DragDropDR103R.dcp from Library\DX103R\Win32_Release folder to  \Users\Public\Documents\Embarcadero\Studio\20.0\Bpl.
(3) Now compiled project dclDragDropDR103R.bpl and copied generated .bpl and .dcp files as above.
(4) Right clicked on dclDragDropDR103R.bpl and 'install'. Design-time 32-bit components installed in IDE.
(5) Set  project DragDropDR103R.bpl to 64-bit and compile. Worked fine. Binaries generated in Library\DX103R\Win64_Release. Copied DragDropDR103R.bpl and DragDropDR103R.dcp from Library\DX103R\Win64_Release folder to  C:\Users\Public\Documents\Embarcadero\Studio\20.0\Bpl\Win64.
(6). Set  project dclDragDropDR103R.bpl to 64-bit and compile. Error generated here that 'designide.dcp' not found. I checked in Emabrcadero "lib" dir, there is only 32bit version supplied and not 64-bit. Since, this is a designtime package, I believe, there is not need to compile this project in 64-bit. right?

With above steps, do you think my application using your components will be 64-bit compliant?

**Comment by landrix** [comment]
There is no 64 Bit design time support in Delphi. And this Option isn't in the design time package

**Comment by landrix** [comment]
The components works under 64-bit. There is only no need for a 64-bit designtime package.

**Comment by vhanla** [comment]
Post Build event for Runtime bpl
`copy "$(OUTPUTDIR)\$(OUTPUTFILENAME)" "$(BDSCOMMONDIR)\Bpl` 
![imagen](https://user-images.githubusercontent.com/1015823/62198737-cf17bc80-b347-11e9-8a72-ca7ad4280569.png)
